name: Convert JSON to ICS

on:
  push:
    branches:
      - main
    paths:
      - events.json  # Only trigger when the events.json file changes
  workflow_dispatch:  # Allow manual trigger

jobs:
  convert-json-to-ics:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ics

    - name: Run Python script to generate ICS
      run: |
        python generate_ics.py

    - name: Commit and push the generated ICS file
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add events.ics
        git commit -m "Update events.ics"
        git push
